### ISSUE TITLE
Call to undefined function the_field()

### ISSUE THREAD

**Issue by tanmalik786** [rjmccollam/Bare-WP#1]
I just tried it on one of my local installs using WP 5.02, and I get this error as soon as I activated the theme

`Fatal error: Uncaught Error: Call to undefined function the_field() in D:\Cloud\MEGA\wamp64\sites\sass-wp5\wp-content\themes\Bare-WP\header.php on line 12`

Regards,

**Comment by rjmccollam** [comment]
This is very likely that you do not have the plugin Advanced Custom Fields installed. That function is a call to the plugin. Install that and you will be all set.

**Comment by tanmalik786** [comment]
Yes, this is true as was not expecting it to rely on a 3rd party plugin like `Advanced Custom Fields` - as a starter theme.
